# Run `just` with no arguments to see this list.
default:
    @just --list

binary_name := "webhook-server"
# The only place aibom-webhook's namespace is configured — the chart itself has no
# separate namespace value, it always installs into the release namespace passed here.
# Override with `just --set webhook_namespace <ns> <recipe>` if it's ever not aibom-system.
webhook_namespace := "aibom-system"

# --- Build & test ------------------------------------------------------------

[group('build')]
build:
    go build -v -o bin/{{ binary_name }} ./cmd/webhook/

# target: all (default), go, or python — run just one suite with `just test go`/`just test python`.
[group('build')]
test target="all":
    #!/usr/bin/env bash
    set -euo pipefail
    case "{{ target }}" in
        all) {{ just_executable() }} _test-go && {{ just_executable() }} _test-python ;;
        go) {{ just_executable() }} _test-go ;;
        python) {{ just_executable() }} _test-python ;;
        *) echo "unknown test target '{{ target }}' (expected all, go, or python)" >&2; exit 1 ;;
    esac

_test-go:
    go test ./internal/... -v -count=1

_test-python:
    python3 -m venv .venv-test
    .venv-test/bin/pip install -q -r requirements-dev.txt
    .venv-test/bin/python -m pytest

[group('build')]
fmt:
    go fmt ./...

[group('build')]
vet:
    go vet ./...

# Run the webhook locally against certs/ generated by scripts/generate-certs.sh
[group('build')]
run: build
    ./bin/{{ binary_name }} --tls-cert=certs/tls.crt --tls-key=certs/tls.key --port=8443

[group('build')]
clean:
    rm -rf bin/ certs/ .venv-test/

# --- Container images ---------------------------------------------------------

[group('images')]
docker-build img="aibom-webhook-service:latest":
    docker build -t {{ img }} .

[group('images')]
docker-push img="aibom-webhook-service:latest":
    docker push {{ img }}

[group('images')]
docker-build-postprocess img="aibom-postprocess:latest":
    docker build -t {{ img }} -f postprocess/Dockerfile .

[group('images')]
docker-push-postprocess img="aibom-postprocess:latest":
    docker push {{ img }}

# --- Cluster deployment --------------------------------------------------------

# Every recipe below that talks to a cluster depends on this, so it always runs first.
_check-auth:
    @oc whoami >/dev/null 2>&1 || { echo "error: not logged in to a cluster — run 'oc login' first" >&2; exit 1; }

# --tag=<tag> sets both the BuildConfig output ImageStreamTag and the Deployment's
# image reference. Defaults to the short SHA scripts/remote-build-sha.sh resolves
# (the commit the BuildConfig is actually about to build) for an immutable,
# rollback-able build — not local HEAD, which can be ahead of, behind, or diverged
# from what the in-cluster build will clone. Pass e.g. --tag=latest to overwrite a
# mutable tag in place instead.
#
# --skip-crds is for accounts without cluster-scoped create/patch permission on the
# CRD/Namespace: it never touches the Namespace object and skips the aiboms.aibom.io
# CRD, which must then already exist — a cluster-admin runs
# `oc apply -f charts/aibom-webhook/crds/aibom-crd.yaml` and creates the namespace once.
#
# Install/upgrade the webhook chart. Requires cert-manager already installed in the cluster.
# Usage: just deploy [--tag=<tag>] [--skip-crds]
[group('deploy')]
deploy *args: _check-auth
    #!/usr/bin/env bash
    set -euo pipefail
    tag=""
    skip_crds=false
    for arg in {{ args }}; do
        case "$arg" in
            --skip-crds) skip_crds=true ;;
            --tag=*) tag="${arg#--tag=}" ;;
            *) echo "error: unknown argument '$arg' (expected --tag=<tag> or --skip-crds)" >&2; exit 1 ;;
        esac
    done
    [ -n "$tag" ] || tag="$(scripts/remote-build-sha.sh)"
    ns_flag="--create-namespace"
    [ "$skip_crds" = true ] && ns_flag="--skip-crds"
    helm upgrade --install aibom-webhook charts/aibom-webhook -n {{ webhook_namespace }} "$ns_flag" \
        --set image.webhook.tag="$tag" --set image.postprocess.tag="$tag"

# Usage: just redeploy [--tag=<tag>] [--skip-crds]
[group('deploy')]
redeploy *args: (deploy args) (_rollout)

_rollout: _check-auth
    oc -n {{ webhook_namespace }} start-build aibom-webhook-service --wait
    oc -n {{ webhook_namespace }} start-build aibom-postprocess --wait
    oc -n {{ webhook_namespace }} delete pods -l openshift.io/build.name --field-selector=status.phase==Succeeded
    oc -n {{ webhook_namespace }} rollout restart deployment/aibom-webhook
    oc -n {{ webhook_namespace }} rollout status deployment/aibom-webhook --timeout=120s
    @echo "NOTE: run 'just setup-namespace <namespace>' for each workload namespace"

[group('deploy')]
[confirm("Uninstall the aibom-webhook release? This removes the webhook, RBAC, and Deployment (the CRD and any AIBOM resources are left in place).")]
undeploy: _check-auth
    helm uninstall aibom-webhook -n {{ webhook_namespace }}

# Namespace must already exist. Installs RBAC + the aibom-scripts ConfigMap via the
# aibom-workload-namespace chart.
#
# Opt an existing namespace into webhook instrumentation by labeling it aibom.io/enabled=true.
[group('deploy')]
setup-namespace namespace: _check-auth
    oc label namespace {{ namespace }} aibom.io/enabled=true --overwrite
    helm upgrade --install aibom-ns-{{ namespace }} charts/aibom-workload-namespace -n {{ namespace }} \
        --set-file scripts.generateSnapshot=scripts/aibom-scripts/generate_snapshot.py \
        --set-file scripts.runtimeDetector=scripts/aibom-scripts/runtime_detector.py \
        --set-file scripts.k8sApi=scripts/aibom-scripts/k8s_api.py
