# Run `just` with no arguments to see this list.
default:
    @just --list

binary_name := "webhook-server"
# The only place aibom-webhook's namespace is configured — the chart itself has no
# separate namespace value, it always installs into the release namespace passed here.
# Override with `just --set webhook_namespace <ns> <recipe>` if it's ever not project-aibom.
webhook_namespace := "project-aibom"

# --- Build & test ------------------------------------------------------------

[group('build')]
build:
    go build -v -o bin/{{ binary_name }} ./cmd/webhook/

# target: all (default), go, or python — run just one suite with `just test go`/`just test python`.
[group('build')]
test target="all":
    #!/usr/bin/env bash
    set -euo pipefail
    case "{{ target }}" in
        all) {{ just_executable() }} _test-go && {{ just_executable() }} _test-python ;;
        go) {{ just_executable() }} _test-go ;;
        python) {{ just_executable() }} _test-python ;;
        *) echo "unknown test target '{{ target }}' (expected all, go, or python)" >&2; exit 1 ;;
    esac

_test-go:
    go test ./internal/... -v -count=1

_test-python:
    python3 -m venv .venv-test
    .venv-test/bin/pip install -q -r requirements-dev.txt
    .venv-test/bin/python -m pytest

[group('build')]
fmt:
    go fmt ./...

[group('build')]
vet:
    go vet ./...

# Run the webhook locally against certs/ generated by scripts/generate-certs.sh
[group('build')]
run: build
    ./bin/{{ binary_name }} --tls-cert=certs/tls.crt --tls-key=certs/tls.key --port=8443

[group('build')]
clean:
    rm -rf bin/ certs/ .venv-test/

# --- Container images ---------------------------------------------------------

[group('images')]
docker-build img="aibom-webhook-service:latest":
    docker build -t {{ img }} .

[group('images')]
docker-push img="aibom-webhook-service:latest":
    docker push {{ img }}

[group('images')]
docker-build-postprocess img="aibom-postprocess:latest":
    docker build -t {{ img }} -f postprocess/Dockerfile .

[group('images')]
docker-push-postprocess img="aibom-postprocess:latest":
    docker push {{ img }}

# --- Cluster deployment --------------------------------------------------------

# Every recipe below that talks to a cluster depends on this, so it always runs first.
_check-auth:
    @oc whoami >/dev/null 2>&1 || { echo "error: not logged in to a cluster — run 'oc login' first" >&2; exit 1; }

# --version=<sha> is the single source of truth for what gets built and how it's
# labeled: it sets the BuildConfig output ImageStreamTag, the Deployment's image
# reference, AND (unless it's "latest") build.gitRef — so the BuildConfig actually
# checks out and builds that exact commit, instead of always cloning whatever
# gitRef's branch currently points to regardless of the tag name. That also pins
# the build to a specific commit rather than the branch tip that could move
# between resolving the version and the build actually cloning it. Defaults to
# the short SHA scripts/remote-build-sha.sh resolves (the remote tip of
# build.gitRef) for an immutable, rollback-able build — not local HEAD, which can
# be ahead of, behind, or diverged from the remote. --version=latest opts back
# into the old behavior: a mutable tag, tracking whatever build.gitRef's branch
# currently is. (Called "version" rather than "tag" since it drives more than
# just the image tag — it's also a git ref, and "tag" overloads both.)
#
# --skip-crds is for accounts without cluster-scoped create/patch permission on the
# CRD/Namespace: it never touches the Namespace object and skips the aiboms.aibom.io
# CRD, which must then already exist — a cluster-admin runs
# `oc apply -f charts/aibom-webhook/crds/aibom-crd.yaml` and creates the namespace once.
# It also drops --kube-as-user=system:admin from the helm call for the same reason —
# that flag requires cluster-admin impersonation rights, which a non-admin install is
# specifically trying to avoid needing.
#
# Install/upgrade the webhook chart, build both images in-cluster from source, and
# roll out the result. Requires cert-manager already installed in the cluster.
# Builds every time: a BuildConfig's ConfigChange trigger only fires automatically
# on its *initial* creation, never on later edits (e.g. a new tag) — so relying on
# the trigger alone would leave subsequent deploys pointing at an unbuilt tag.
#
# The opt-in path for clusters that specifically want in-cluster builds instead of
# pulling Quay-built images (`just deploy` is the seamless default — see there).
# values.yaml defaults to build.enabled=false, so this recipe explicitly sets
# build.enabled=true and points image.*.repository back at the in-cluster registry
# path the BuildConfig actually writes to — the two must move together, or the
# Deployment ends up pointed at an image the BuildConfig never produced.
#
# With no arguments, deploys build.gitRef from values.yaml (master) at its current
# remote tip — NOT your local checkout or branch, which this recipe never inspects.
# --branch[=<name>] deploys a different branch instead: defaults to whatever branch
# is currently checked out locally if no name is given, resolves it to its remote
# tip SHA via remote-build-sha.sh (erroring if it hasn't been pushed), and uses that
# SHA the same way --version would — so it's still pinned to immutable content, not
# a mutable branch name that could move between resolving and building it.
# Usage: just deploy-buildconfig [--version=<sha> | --branch[=<name>]] [--values=<file>] [--skip-crds]
[group('deploy')]
deploy-buildconfig *args: _check-auth
    #!/usr/bin/env bash
    set -euo pipefail
    version=""
    branch=""
    values_file=""
    skip_crds=false
    for arg in {{ args }}; do
        case "$arg" in
            --skip-crds) skip_crds=true ;;
            --version=*) version="${arg#--version=}" ;;
            --values=*) values_file="${arg#--values=}" ;;
            --branch) branch="$(git rev-parse --abbrev-ref HEAD)" ;;
            --branch=*) branch="${arg#--branch=}" ;;
            *) echo "error: unknown argument '$arg' (expected --version=<sha>, --branch[=<name>], --values=<file>, or --skip-crds)" >&2; exit 1 ;;
        esac
    done
    if [[ -n "$version" && -n "$branch" ]]; then
        echo "error: --version and --branch are mutually exclusive" >&2
        exit 1
    fi
    if [[ -n "$branch" ]]; then
        version="$(scripts/remote-build-sha.sh "$branch")"
    fi
    [[ -n "$version" ]] || version="$(scripts/remote-build-sha.sh)"
    ns_flag="--create-namespace"
    [[ "$skip_crds" = true ]] && ns_flag="--skip-crds"
    kube_as_user_args=()
    [[ "$skip_crds" = true ]] || kube_as_user_args=(--kube-as-user=system:admin)
    values_args=()
    [[ -n "$values_file" ]] && values_args=(-f "$values_file")
    gitref_args=()
    [[ "$version" = "latest" ]] || gitref_args=(--set "build.gitRef=$version")
    first_install=false
    helm status aibom-webhook -n {{ webhook_namespace }} >/dev/null 2>&1 || first_install=true
    helm upgrade --install aibom-webhook charts/aibom-webhook -n {{ webhook_namespace }} "$ns_flag" \
        "${kube_as_user_args[@]}" \
        "${values_args[@]}" \
        --set build.enabled=true \
        --set image.webhook.repository="image-registry.openshift-image-registry.svc:5000/{{ webhook_namespace }}/aibom-webhook-service" \
        --set image.postprocess.repository="image-registry.openshift-image-registry.svc:5000/{{ webhook_namespace }}/aibom-postprocess" \
        --set image.webhook.tag="$version" --set image.postprocess.tag="$version" "${gitref_args[@]}"
    if [[ "$first_install" = true ]]; then
        # The BuildConfigs' ConfigChange trigger already auto-fired an initial build the
        # moment they were just created above — starting another would just double build
        # time. Wait on that auto-triggered build (always numbered -1) instead.
        echo "first install: waiting on the auto-triggered initial builds instead of starting redundant ones"
        for bc in aibom-webhook-service aibom-postprocess; do
            for i in $(seq 1 30); do
                oc -n {{ webhook_namespace }} get "build/${bc}-1" >/dev/null 2>&1 && break
                sleep 1
            done
            oc -n {{ webhook_namespace }} wait --for=condition=Complete "build/${bc}-1" --timeout=300s
        done
    else
        # latest is intentionally mutable — always rebuild it. Any other version is an
        # immutable per-commit tag: if it's already been built (and not since pruned),
        # rebuilding would just reproduce the same content, so skip it.
        for bc in aibom-webhook-service aibom-postprocess; do
            if [ "$version" != "latest" ] && oc -n {{ webhook_namespace }} get istag "${bc}:${version}" >/dev/null 2>&1; then
                echo "${bc}:${version} already built — skipping rebuild"
            else
                oc -n {{ webhook_namespace }} start-build "$bc" --wait
            fi
        done
    fi
    oc -n {{ webhook_namespace }} delete pods -l openshift.io/build.name --field-selector=status.phase==Succeeded
    oc -n {{ webhook_namespace }} rollout restart deployment/aibom-webhook
    oc -n {{ webhook_namespace }} rollout status deployment/aibom-webhook --timeout=120s
    echo "NOTE: run 'just setup-namespace <namespace>' for each workload namespace"

# Usage: just undeploy [--skip-crds]
#
# The chart's cluster-scoped RBAC (ClusterRole/ClusterRoleBinding) and the
# MutatingWebhookConfiguration are owned by this release too, so `helm uninstall`
# needs the same cluster-admin impersonation `deploy`/`deploy-buildconfig`/
# `deploy-local` need to install them — without it, expect a partial uninstall
# that removes namespace-scoped resources but errors out on (and leaves behind)
# the cluster-scoped ones. --skip-crds mirrors the deploy recipes' flag name for
# consistency, dropping --kube-as-user=system:admin for a caller who already
# holds that permission some other way — nothing here actually touches the
# aiboms.aibom.io CRD, which `helm uninstall` never removes regardless (see the
# confirmation message below).
[group('deploy')]
[confirm("Uninstall the aibom-webhook release? This removes the webhook, RBAC, and Deployment (the CRD and any AIBOM resources are left in place).")]
undeploy *args: _check-auth
    #!/usr/bin/env bash
    set -euo pipefail
    skip_crds=false
    for arg in {{ args }}; do
        case "$arg" in
            --skip-crds) skip_crds=true ;;
            *) echo "error: unknown argument '$arg' (expected --skip-crds)" >&2; exit 1 ;;
        esac
    done
    kube_as_user_args=()
    [[ "$skip_crds" = true ]] || kube_as_user_args=(--kube-as-user=system:admin)
    helm uninstall aibom-webhook -n {{ webhook_namespace }} "${kube_as_user_args[@]}"

# Build both images locally and push them to quay.io, then install/upgrade the
# chart with build.enabled=false so the Deployment pulls those pushed images
# instead of the in-cluster BuildConfig path `just deploy-buildconfig` uses. Useful for
# iterating without a git-push round trip, or on a cluster with no route to
# the source repo. Unlike OpenShift's own internal registry (not reachable
# from outside the cluster without a cluster-admin exposing its route — not a
# safe assumption to make by default), quay.io is reachable from anywhere the
# caller already has push access, with no cluster-side permission needed.
#
# repo is the quay.io org/user to push under, e.g. quay.io/<your-org> — the
# two image names (aibom-webhook-service, aibom-postprocess) are appended
# automatically. Requires the caller already logged in (`docker login quay.io`
# / `podman login quay.io`) with push access to that repo.
#
# Defaults to the local working tree's short SHA, suffixed "-dirty" if there
# are uncommitted changes — unlike `just deploy-buildconfig`, there's no git
# remote tip to resolve here, since this builds whatever's on disk right now.
# --skip-crds behaves the same as in `just deploy-buildconfig`.
# Usage: just deploy-local <repo> [--version=<tag>] [--values=<file>] [--skip-crds]
[group('deploy')]
deploy-local repo *args: _check-auth
    #!/usr/bin/env bash
    set -euo pipefail
    engine=docker
    command -v docker >/dev/null 2>&1 || engine=podman
    version=""
    values_file=""
    skip_crds=false
    for arg in {{ args }}; do
        case "$arg" in
            --skip-crds) skip_crds=true ;;
            --version=*) version="${arg#--version=}" ;;
            --values=*) values_file="${arg#--values=}" ;;
            *) echo "error: unknown argument '$arg' (expected --version=<tag>, --values=<file>, or --skip-crds)" >&2; exit 1 ;;
        esac
    done
    if [[ -z "$version" ]]; then
        version="$(git rev-parse --short HEAD)"
        git diff --quiet HEAD || version="${version}-dirty"
    fi
    webhook_ref="{{ repo }}/aibom-webhook-service:${version}"
    postprocess_ref="{{ repo }}/aibom-postprocess:${version}"
    "$engine" build -t "$webhook_ref" .
    "$engine" build -t "$postprocess_ref" -f postprocess/Dockerfile .
    "$engine" push "$webhook_ref"
    "$engine" push "$postprocess_ref"
    ns_flag="--create-namespace"
    [[ "$skip_crds" = true ]] && ns_flag="--skip-crds"
    kube_as_user_args=()
    [[ "$skip_crds" = true ]] || kube_as_user_args=(--kube-as-user=system:admin)
    values_args=()
    [[ -n "$values_file" ]] && values_args=(-f "$values_file")
    helm upgrade --install aibom-webhook charts/aibom-webhook -n {{ webhook_namespace }} "$ns_flag" \
        "${kube_as_user_args[@]}" \
        "${values_args[@]}" \
        --set build.enabled=false \
        --set image.webhook.repository="{{ repo }}/aibom-webhook-service" \
        --set image.postprocess.repository="{{ repo }}/aibom-postprocess" \
        --set image.webhook.tag="$version" --set image.postprocess.tag="$version"
    oc -n {{ webhook_namespace }} rollout restart deployment/aibom-webhook
    oc -n {{ webhook_namespace }} rollout status deployment/aibom-webhook --timeout=120s
    echo "NOTE: run 'just setup-namespace <namespace>' for each workload namespace"

# The seamless default: install/upgrade the chart against images Quay already
# built — no build, no push, just a helm install pointing at a tag. Works once
# Quay's GitHub build triggers are set up (see README) to auto-build both
# images on every push to master: nothing runs locally at all, this just tells
# the cluster where to pull from. Also matches values.yaml's own defaults
# (quay.io/gsanders, tag latest), so `just deploy` with no arguments is
# equivalent to a plain `helm upgrade --install` with no --set overrides —
# repo/version only matter when deploying a different quay org or pinning to
# an immutable SHA tag instead of the mutable "latest" Quay's master trigger
# keeps overwriting. For in-cluster builds instead, see `just deploy-buildconfig`.
# Usage: just deploy [<repo>] [--version=<tag>] [--values=<file>] [--skip-crds]
[group('deploy')]
deploy repo="quay.io/gsanders" *args: _check-auth
    #!/usr/bin/env bash
    set -euo pipefail
    version="latest"
    values_file=""
    skip_crds=false
    for arg in {{ args }}; do
        case "$arg" in
            --skip-crds) skip_crds=true ;;
            --version=*) version="${arg#--version=}" ;;
            --values=*) values_file="${arg#--values=}" ;;
            *) echo "error: unknown argument '$arg' (expected --version=<tag>, --values=<file>, or --skip-crds)" >&2; exit 1 ;;
        esac
    done
    ns_flag="--create-namespace"
    [[ "$skip_crds" = true ]] && ns_flag="--skip-crds"
    kube_as_user_args=()
    [[ "$skip_crds" = true ]] || kube_as_user_args=(--kube-as-user=system:admin)
    values_args=()
    [[ -n "$values_file" ]] && values_args=(-f "$values_file")
    helm upgrade --install aibom-webhook charts/aibom-webhook -n {{ webhook_namespace }} "$ns_flag" \
        "${kube_as_user_args[@]}" \
        "${values_args[@]}" \
        --set build.enabled=false \
        --set image.webhook.repository="{{ repo }}/aibom-webhook-service" \
        --set image.postprocess.repository="{{ repo }}/aibom-postprocess" \
        --set image.webhook.tag="$version" --set image.postprocess.tag="$version"
    oc -n {{ webhook_namespace }} rollout restart deployment/aibom-webhook
    oc -n {{ webhook_namespace }} rollout status deployment/aibom-webhook --timeout=120s
    echo "NOTE: run 'just setup-namespace <namespace>' for each workload namespace"

# --- Local kind cluster --------------------------------------------------------
#
# Not OpenShift — no BuildConfig/ImageStream, no oc. Provider (docker vs podman)
# is auto-detected the same way mock-openshift-cluster's scripts/lib.sh picks it
# for `just up`/`just down`: docker unless its daemon is unreachable. This has
# to match exactly — kind tracks clusters per-provider, so loading images via
# the wrong provider silently creates/targets a second, empty "mock-openshift"
# cluster instead of erroring, and every pod on the real one sits in
# ImagePullBackOff since the image never actually landed on its node.
# build.enabled is set to false on deploy (that template is OpenShift-only)
# and image.*.repository/tag point at the locally-loaded tags instead of the
# in-cluster registry. Requires the kind cluster to already be up with
# cert-manager installed (templates/certificates.yaml still needs it).

kind_cluster_name := "mock-openshift"
kind_webhook_img := "localhost/aibom-webhook-service:dev"
kind_postprocess_img := "localhost/aibom-postprocess:dev"

[group('kind')]
kind-image:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ -z "${KIND_EXPERIMENTAL_PROVIDER:-}" ] && ! docker info >/dev/null 2>&1 && command -v podman >/dev/null 2>&1; then
        export KIND_EXPERIMENTAL_PROVIDER=podman
    fi
    engine=podman
    command -v docker >/dev/null 2>&1 && [ "${KIND_EXPERIMENTAL_PROVIDER:-}" != "podman" ] && engine=docker
    "$engine" build -t {{ kind_webhook_img }} .
    "$engine" build -t {{ kind_postprocess_img }} -f postprocess/Dockerfile .
    tar_webhook="$(mktemp -t aibom-webhook-kind-XXXXXX.tar)"
    tar_postprocess="$(mktemp -t aibom-postprocess-kind-XXXXXX.tar)"
    trap 'rm -f "$tar_webhook" "$tar_postprocess"' EXIT
    "$engine" save {{ kind_webhook_img }} -o "$tar_webhook"
    "$engine" save {{ kind_postprocess_img }} -o "$tar_postprocess"
    kind load image-archive "$tar_webhook" --name {{ kind_cluster_name }}
    kind load image-archive "$tar_postprocess" --name {{ kind_cluster_name }}

# Build+load both images, then install/upgrade the webhook chart against them.
# Requires the kind cluster to already be up.
[group('kind')]
kind-deploy: kind-image
    helm upgrade --install aibom-webhook charts/aibom-webhook -n {{ webhook_namespace }} --create-namespace \
        --kube-context kind-{{ kind_cluster_name }} \
        --set build.enabled=false \
        --set image.webhook.repository=localhost/aibom-webhook-service --set image.webhook.tag=dev \
        --set image.postprocess.repository=localhost/aibom-postprocess --set image.postprocess.tag=dev \
        --set image.pullPolicy=IfNotPresent
    kubectl --context kind-{{ kind_cluster_name }} -n {{ webhook_namespace }} rollout restart deployment/aibom-webhook
    kubectl --context kind-{{ kind_cluster_name }} -n {{ webhook_namespace }} rollout status deployment/aibom-webhook --timeout=120s

[group('kind')]
[confirm("Uninstall the aibom-webhook release from the kind cluster?")]
kind-undeploy:
    helm uninstall aibom-webhook -n {{ webhook_namespace }} --kube-context kind-{{ kind_cluster_name }}

# Namespace must already exist. Installs RBAC + the aibom-scripts ConfigMap via the
# aibom-workload-namespace chart.
#
# Opt an existing namespace into webhook instrumentation by labeling it aibom.io/enabled=true.
# Pass skip_label=true to leave the namespace label alone (e.g. it's already labeled, or
# labeling is managed elsewhere) — also skips --kube-as-user=system:admin on the helm call,
# since the chart creates a ClusterRoleBinding and a cross-namespace RoleBinding into
# aibom-system, neither of which a namespace-scoped admin can create on their own; a caller
# who already labeled the namespace themselves (skip_label=true) is assumed to also already
# hold the cluster-scoped RBAC this needs some other way.
[group('deploy')]
setup-namespace namespace skip_label="false": _check-auth
    #!/usr/bin/env bash
    set -euo pipefail
    kube_as_user_args=()
    if [ "{{ skip_label }}" != "true" ]; then
        oc label namespace {{ namespace }} aibom.io/enabled=true --overwrite
        kube_as_user_args=(--kube-as-user=system:admin)
    fi
    helm upgrade --install aibom-ns-{{ namespace }} charts/aibom-workload-namespace -n {{ namespace }} \
        "${kube_as_user_args[@]}" \
        --set-file scripts.generateSnapshot=scripts/aibom-scripts/generate_snapshot.py \
        --set-file scripts.runtimeDetector=scripts/aibom-scripts/runtime_detector.py \
        --set-file scripts.k8sApi=scripts/aibom-scripts/k8s_api.py

# Reverses `just setup-namespace`: uninstalls the aibom-ns-<namespace> release
# (removing the image-puller RoleBinding, aibom-scripts ConfigMap, aibom-postprocess
# ServiceAccount/RBAC, aibom-workload-data/aibom-workload-inferenceservices RBAC, the
# discovery-HMAC Secret, and the cluster-scoped ClusterRoleBinding it created) and
# removes the aibom.io/enabled label. Needs the same cluster-admin impersonation as
# setup-namespace and for the same reason — the ClusterRoleBinding/cross-namespace
# RoleBinding this release owns aren't things a namespace-scoped admin can delete
# either. Pass skip_label=true to leave the label alone and skip impersonation,
# mirroring setup-namespace's flag.
[group('deploy')]
[confirm("Uninstall the aibom-ns-<namespace> release and remove the aibom.io/enabled label from that namespace?")]
uninstall-namespace namespace skip_label="false": _check-auth
    #!/usr/bin/env bash
    set -euo pipefail
    kube_as_user_args=()
    [[ "{{ skip_label }}" = "true" ]] || kube_as_user_args=(--kube-as-user=system:admin)
    helm uninstall aibom-ns-{{ namespace }} -n {{ namespace }} "${kube_as_user_args[@]}"
    if [ "{{ skip_label }}" != "true" ]; then
        oc label namespace {{ namespace }} aibom.io/enabled- --as=system:admin
    fi

# --- Chart publishing -----------------------------------------------------
#
# Packages both charts and pushes them as OCI artifacts to Quay, so
# `helm upgrade --install ... oci://quay.io/<org>/aibom-webhook` and
# `.../aibom-workload-namespace` (chart names, distinct from the
# aibom-webhook-service/aibom-postprocess image repos) work with no checked-out
# copy of this repo. One-time setup: `helm registry login quay.io` with an
# account/robot that has push access under that org, and (in the Quay UI) make
# both chart repos public, or install accepts credentials some other way.
#
# The aibom-workload-namespace chart needs scripts/aibom-scripts/*.py embedded
# so an OCI install doesn't also need --set-file pointed at a repo checkout —
# copied into charts/aibom-workload-namespace/files/ here (gitignored; picked
# up by templates/scripts-configmap.yaml as a fallback only when
# .Values.scripts.* isn't set — see that file) rather than committed, so
# there's exactly one source of truth for the scripts and this recipe is the
# only place responsible for keeping the packaged copy fresh.
[group('charts')]
chart-push repo="quay.io/gsanders":
    #!/usr/bin/env bash
    set -euo pipefail
    pkg_dir="$(mktemp -d)"
    trap 'rm -rf charts/aibom-workload-namespace/files "$pkg_dir"' EXIT
    rm -rf charts/aibom-workload-namespace/files
    mkdir -p charts/aibom-workload-namespace/files
    cp scripts/aibom-scripts/generate_snapshot.py scripts/aibom-scripts/runtime_detector.py \
        scripts/aibom-scripts/k8s_api.py charts/aibom-workload-namespace/files/
    helm package charts/aibom-webhook -d "$pkg_dir"
    helm package charts/aibom-workload-namespace -d "$pkg_dir"
    helm push "$pkg_dir"/aibom-webhook-*.tgz oci://{{ repo }}
    helm push "$pkg_dir"/aibom-workload-namespace-*.tgz oci://{{ repo }}
