apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: aibom-webhook
webhooks:
  - name: aibom-webhook.aibom-system.svc
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Ignore
    reinvocationPolicy: Never
    namespaceSelector:
      matchLabels:
        aibom.io/enabled: "true"
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: Namespaced
    clientConfig:
      service:
        name: aibom-webhook
        namespace: aibom-system
        path: /mutate
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURGekNDQWYrZ0F3SUJBZ0lVRmF2RmlnaFB2UDNXMDZUeEF1VlA5Zzh4NWt3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0d6RVpNQmNHQTFVRUF3d1FZV2xpYjIwdGQyVmlhRzl2YXkxallUQWVGdzB5TmpBM01qSXhOek0wTVRGYQpGdzB5TnpBM01qSXhOek0wTVRGYU1Cc3hHVEFYQmdOVkJBTU1FR0ZwWW05dExYZGxZbWh2YjJzdFkyRXdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFQzNHdhQ1dNemhwV1pRcFlJWVZOc2hqNE0KQ0NqWEthOHZveEFvN1FLb3JheFJEZ3lhVGNKeEFEL1ZUM0N0WXdURzBwc1lGZGswM1BwTUhiK0tHTmkxQW9SdApYeU5ocE9WWlpPWG40M2Z2TS95MG82R2E3ZklZeWVpL1RsdFJJbm11TVVBc3dLelpuSmc2ck0xakNqNXplQ3RMClAzZDVNNG5KTmV6cUF2MldwVjVOODZtQ1dTWWk1QVQyZFV1NW5CS0w2czdHZ2d3YmU5bW1MRXdrdFJzaFNMRFUKQUFPdS9Zbzh4RVBnQTVWb21GU0YwdCtnT1d5RVdidFpYUkhzdDFpWTBWVnZmTXlGaGlSVHVkQTduSzVIWDFCSgpOZ2ZRMXltYnBMdFpMLzN2UXhzeVVIOHFwZ0tTNy95UjJpaTkzOVBWY2NzZTBtR2RwWWpEL1FncEtWb3BBZ01CCkFBR2pVekJSTUIwR0ExVWREZ1FXQkJRWU5ZSGordENxcDlRZmlTQURCVldxa1BqNVpqQWZCZ05WSFNNRUdEQVcKZ0JRWU5ZSGordENxcDlRZmlTQURCVldxa1BqNVpqQVBCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUURHbkZ1Vi9aa3JPUDZ4ZkRPMVA4U1RyZ1NaT01nQWZ5Z2RXQjQ2Znl4dWxRS0V6WElhCm1lUEJtZVJZZ1plYktoNENCMDZ2N25ZN1JEeUlzbnJCWVBPdUY3d0k5ME1LazBDYllrbGNodGNGZlVXcGtTZDgKTjUrWG5KT1EyWFY0MmdVckt6cERJWTRNRlNNc05jSjlsUFl5THI0YUVnWmVSQnVmbGRKUFVXQUEwV29WVXphQgpUVVMvcExIVjRTQmxsWHN1dUtzOWtPN3g4akY3ejFVdGxSbkxrWVlmZVA2bFEvTTJsdHNIZG9PdExGeWVqbkU5CmpyR0pPLzE0TjNXTVRMRnVrd1RQN3Rhc01MZ1lMY01UU0VXUW1VbndreTl5L3NCdTVKKzlvTERFRWt0a1BpSSsKcEpTN081elVBT3c4eDlJUHhUY0drbEozVllMUHVPdjFBTlRZCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
