{{- if .Values.build.enabled }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: aibom-webhook-service
  namespace: {{ include "aibom-webhook.namespace" . }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: aibom-webhook-service
  namespace: {{ include "aibom-webhook.namespace" . }}
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.build.gitRepo }}
      ref: {{ .Values.build.gitRef }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: aibom-webhook-service:latest
  triggers:
    - type: ConfigChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: aibom-postprocess
  namespace: {{ include "aibom-webhook.namespace" . }}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: aibom-postprocess
  namespace: {{ include "aibom-webhook.namespace" . }}
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.build.gitRepo }}
      ref: {{ .Values.build.gitRef }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: postprocess/Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: aibom-postprocess:latest
  triggers:
    - type: ConfigChange
{{- end }}
