apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aibom-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aibom-webhook
subjects:
  - kind: ServiceAccount
    name: aibom-webhook
    namespace: {{ include "aibom-webhook.namespace" . }}
